name: adit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  flutter:
    sdk: flutter
  freezed: ^2.5.7
  hooks_riverpod: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
